@Pizza.API_HostAddress = https://localhost:7228


POST {{Pizza.API_HostAddress}}/api/register/register
Content-Type: application/json

{
 Name: "John Doe",
 Email: "emaspfsdkf@gmail.com",
 Password: "123556"
}

###

